version: "3.7"

networks:
  app-network:

services:
  managedhost-app-1:
    build: 
      context: managed-host/alpine/app1
    restart: unless-stopped
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - 3000:3000
      - 2223:2223
    networks:
      - app-network

  managedhost-app-2:
    build: 
      context: managed-host/alpine/app2
    restart: unless-stopped
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - 3001:3000
      - 2224:2224
    networks:
      - app-network

  managedhost-app-3:
    build: 
      context: managed-host/alpine/app3
    restart: unless-stopped
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - 3002:3000
      - 2225:2225
    networks:
      - app-network
  
  loadbalancer:
    build: 
      context: managed-host/alpine/loadbalancer
    restart: unless-stopped
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
      - ssh-keys:/etc/ssh/keys
    ports:
      - 80:80
      - 2226:2226
    networks:
      - app-network
volumes:
  ssh-keys: