all:
  children:
    app_group:
      hosts:
        managedhost-app-1:
          ansible_host: 0.0.0.0
          ansible_port: 2223
          ansible_user: root
        managedhost-app-2:
          ansible_host: 0.0.0.0
          ansible_port: 2224
          ansible_user: root
        managedhost-app-3:
          ansible_host: 0.0.0.0
          ansible_port: 2225
          ansible_user: root
    loadbalancer_group:
      hosts:
        loadbalancer:
          ansible_host: 0.0.0.0
          ansible_port: 2226
          ansible_user: root